export enum pokemonType {
    grass = "Grass",
    fire = "Fire",
    water = "Water",
    ice = "Ice",
    fighting = "Fighting",
    normal = "Normal",
    flying = "Flying",
    psychic = "Psychic",
    ground = "Ground",
    poison = "Poison",
    dragon = "Dragon",
    electric = "Electric",
    ghost = "Ghost",
    dark = "Dark",
    rock = "Rock",
    steel = "Steel",
    fairy = "Fairy",
    bug = "Bug"
}